channels:
- conda-forge
dependencies:
- python=3.10.16
- pip<=25.0.1
- pip:
  - mlflow==2.20.2
  - numpy==2.2.3
  - pandas==2.2.3
  - psutil==6.1.1
  - scikit-learn==1.6.1
  - scipy==1.15.2
  - xgboost==2.1.4
name: mlflow-env
